User.destroy_all
Product.destroy_all
Post.destroy_all
Part.destroy_all

# USERS
brian = User.create(username: "brian", password: "pw")
testuser = User.create(username: "test", password: "test")
################################################################ PRODUCTS #############################################################################
# KICKZ
travi1 = Product.create(name: "Travis Scott x Air Jordan 1 Retro High OG 'Mocha'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/018/783/118/original/488879_01.jpg.jpeg", description: "The Travis Scott x Air Jordan 1 Retro High features a new look on the iconic silhouette, thanks to an oversized backward-facing Swoosh on the lateral side. A traditionally oriented Swoosh graces the medial side of the upper, which is built with a blend of white leather and brown suede. Additional unique details include a double-layer construction on the collar and Scott’s crudely drawn face logo embossed on the heel.")
raidBlackFOG = Product.create(name:"Air Fear Of God Raid 'Black'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/021/545/556/original/489359_01.jpg.jpeg", description: "Nike and frequent collaborator Fear Of God designer, Jerry Lorenzo, joined forces once again for the Air Fear Of God Raid 'Black' sneaker. Released in May 2019, the uniquely designed silhouette is inspired by one of Lorenzo’s favorite Nike designs, the Air Raid. Outfitted with a cross strap suede and textile upper above; below, its equipped with a double stacked Zoom Air unit in heel for a retro, yet futuristic finish.")
uncOffWhites = Product.create(name: "OFF-WHITE x Air Jordan 1 Retro High OG 'UNC'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/012/219/525/original/335047_01.jpg.jpeg", description: "Inspired by Michael Jordan’s alma mater, the Off-White x Air Jordan 1 Retro High OG ‘UNC’ carries a classic two-tone composition, filtered through Virgil Abloh’s unique design prism. The process involves taking a white leather base with dark powder blue overlays and adding embellishments that convey an expressive, handmade quality. They include detached Wings, a floating Swoosh, and lines of text on the medial-side quarter panel delineating the taxonomy of the shoe.")
travi4 = Product.create(name: "Travis Scott x Air Jordan 4 Retro 'Cactus Jack'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/012/478/528/original/365514_01.jpg.jpeg", description: "Music artist Travis Scott hails from Houston, where the Oilers used to take the field in red, white and blue uniforms. The Travis Scott x Air Jordan 4 Retro 'Cactus Jack' colorway pays tribute to the city’s bygone football team with a Durabuck leather upper dressed in University Blue and a Varsity Red insole. The black lace cage and a heel panel feature a light blue speckle pattern. Cactus Jack branding appears on the left heel in Varsity Red, with a matching Jumpman logo on the right.")
bredToe1 = Product.create(name: "Air Jordan 1 Retro High OG 'Bred Toe'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/010/222/921/original/144690_01.jpg.jpeg", description: "Arriving in stores in February 2018, the Air Jordan 1 Retro High OG ‘Bred Toe’ is a new spin on a classic design. The Chicago Bulls-inspired colorway combines elements of the ‘Bred’ and ‘Black Toe’ editions of the Air Jordan 1, executed on a premium leather build. The high-top features a black Swoosh on the white quarter panel, along with contrasting pops of red on the toe box, heel, collar, and outsole. The shoe stays true to its OG 1985 roots with Nike Air branding on the tongue tag and sockliner.")
shadow1 = Product.create(name: "Air Jordan 1 Retro High OG 'Shadow' 2018", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/011/120/009/original/218099_01.jpg.jpeg", description: "This Nike Air Jordan 1 Retro High OG 'Shadow' 2018 is a retro re-release of an original 1985 colorway. The shoe features a black and medium grey leather upper with a white midsole and black outsole. It also features OG Nike Air branding on the tongue and the Wings logo on the ankle collar. It was last retroed in 2013, and a low-top version dropped in 2015.")
traviAf1 = Product.create(name: "Travis Scott x Air Force 1 'Sail'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/013/832/094/original/306892_01.jpg.jpeg", description: "The ‘Sail’ colorway of Travis Scott’s Air Force 1 represents the Houston rapper’s second collaboration with Nike on the classic silhouette. Aside from swapping out the all-white finish of its predecessor with slightly darker Sail, the new model is mostly unchanged. Tonal canvas construction is accented with removable Swooshes and tongue patches, while the shiny lace jewels give a nod to Scott’s signature grill.")
vmOffWhite = Product.create(name: "OFF-WHITE x Air VaporMax 'Part 2'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/010/564/076/original/303229_01.jpg.jpeg", description: "The April 2018 version of Virgil Abloh’s all-white Air VaporMax is mostly unchanged from the original pair from ‘The Ten.’ Stripped of color, the performance runner brings raw materials and unique details to the forefront, including an exposed-foam tongue, translucent Swoosh and off-white suede eyestay. Printed above the clear VaporMax unit, the quotation ‘AIR’ print on the lateral side takes on an extra meta dimension.")
fcrbhoodie = Product.create(name: "BAPE X FCRB TEAM HOODIE", img_url: "https://cdn.shopify.com/s/files/1/0214/3706/products/001PPF231901_BLK_A_1024x1024.jpg?v=1553287763", description: "Cut and Sewn BAPE X FCRB Team Hoodie - Mens - Black")
atmosam1 = Product.create(name: "Atmos x Air Jordan x Air Max 1 'Elephant'", img_url: "https://image.goat.com/crop/750/attachments/product_template_pictures/images/002/949/553/original/923093_001.png.png", description: "Back in 2006, Japanese retailer atmos partnered up with Nike for an exclusive colorway that infused the classic Air Max 1 silhouette with unique features. To celebrate the 10-year anniversary of the collaboration, they re-released the original colorway. The atmos x Air Jordan x Air Max 1 'Elephant' features a white-based upper with black suede overlays on the side, forefoot, and heel. The sneaker also boasts the iconic elephant print along the mudguard and ankle collar, Clear Jade details on the branding, and a partially encapsulated Air unit in the midsole. A Jumpman logo can be found underneath the translucent sole.")
bred4 = Product.create(name: "Air Jordan 4 Retro OG 'Bred' 2019", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/020/806/492/original/461782_01.jpg.jpeg", description: "The 2019 edition of the Air Jordan 4 ‘Bred’ celebrates the 30th anniversary of the classic silhouette, appearing in the same colorway that Michael Jordan wore when he sank ‘The Shot’ during the first round of the 1989 NBA playoffs. It’s rendered in a build that’s faithful to the original, complete with a black nubuck upper, visible Air Sole cushioning underfoot and Nike Air branding on the heel.")
waverunner = Product.create(name: "Yeezy Boost 700 'Wave Runner'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/014/507/858/original/195483_01.jpg.jpeg", description: "This inaugural colorway of Kanye West’s Yeezy Wave Runner 700 launched in November 2017, following a public debut earlier in the year as part of the Yeezy Season 5 runway show. The sneaker’s retro-inspired lines worked in tandem with a chunky silhouette reminiscent of an earlier era. A mesh base is finished in grey on the quarter panels and bright blue and teal on the forefoot. Suede overlays arrive on the toe and heel accented grey leather eyestays. Other details include neon green laces, a bulky white midsole, and pops of black and bright orange.")
shatterAway = Product.create(name: "Air Jordan 1 Retro High OG 'Shattered Backboard Away'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/008/491/815/original/70878_01.jpg.jpeg", description: "In 1985 on a Nike Europe tour, Michael Jordan shattered a backboard when throwing down a monstrous dunk while wearing an orange, black, and white uniform. Commemorating the moment and uniform, a 2015 Air Jordan 1 'Shattered Backboard' (aka 'Shattered Backboard' 1.0) sneaker was released. Shortly after in the Fall of 2016, an Air Jordan 1 'Shattered Backboard Away' (aka 'Reverse' and 'Shattered Backboard 2.0') was released. This sneaker keeps the black laces and Nike branding, but swaps out the orange toe box and black around the toe and tongue for white.")
frag = Product.create(name: "Fragment Design x Air Jordan 1 Retro High OG 'Fragment'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/008/488/331/original/14957_01.jpg.jpeg", description: "The Nike Fragment Design x Air Jordan 1 Retro High OG is the first collaboration between Hiroshi Fujiwara's Fragment Design and Brand Jordan. One of the most coveted Air Jordan 1 colorways ever created, the design combines the OG black-toe color blocking with royal blue accents. Released in limited quantities in December 2014, the design also includes Nike Air branding on the tongue and a Fragment Design logo at the heel.")
offWhiteChicago = Product.create(name: "OFF-WHITE x Air Jordan 1 Retro High OG 'Chicago'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/008/487/311/original/136666_01.jpg.jpeg", description: "Created by designer Virgil Abloh, the Air Jordan 1 x OFF-WHITE comes in the classic Chicago colorway. Some of the sneakers' half-finished features include a Swoosh connected to the shoe with visible blue stitching, 'Air' printed on the midsole, and an OFF-WHITE zip tie on the collar. The box comes deconstructed as it's been turned inside-out with the inside consisting of a black base and gold Jumpman logo, while the outside is plain cardboard with the words 'Jumpman' printed on it. Virgil's OFF-WHITE collection included remixed iterations of the Air VaporMax, Air Presto, Air Max 90, Blazer, Air Max 97, Hyperdunk 2017, Air Force 1, Zoom Fly, and Chuck Taylor.")
wotherspoon = Product.create(name: "Sean Wotherspoon x Air Max 1/97 'Sean Wotherspoon'", img_url: "https://image.goat.com/crop/750/attachments/product_template_additional_pictures/images/011/255/124/original/329483_01.jpg.jpeg", description: "Released for Air Max Day in 2018, this Sean Wotherspoon designed hybrid won the ‘Vote Forward’ campaign. This new creation combines the upper of an Air Max 97 with an Air Max 1 sole. The shoe features a retro-inspired multicolored corduroy upper with corduroy pull tabs, Velcro tongue patches, and an Infrared Air unit.")

# TOPS
cycleJacket = Product.create(name: "PASTEL COLOR CYCLE JACKET", img_url: "https://cdn.shopify.com/s/files/1/0214/3706/products/001LJF301015_PUR_A_1024x1024.jpg?v=1552677973", description: "Jacket - Pastel Color Cycle Jacket - Mens - Purple")
camoFullZipBape = Product.create(name: "1ST CAMO FULL ZIP HOODIE MENS", img_url: "https://cdn.shopify.com/s/files/1/0214/3706/products/001ZPF301009_YEL_A_large.jpg?v=1553278169", description: "100% Cotton Full Zip Bape Hoodie - Yellow Camo")
greenPastalBigLogoHoodie = Product.create(name: "Pastal Color Big Logo Wide Pullover Hoodie", img_url: "https://cdn.shopify.com/s/files/1/0214/3706/products/001PPF301008_GRN_A_1024x1024.jpg?v=1552680046" , description: "Green pastal colorway - Big Logo Wide Pullover Hoodie")
supremeSLogoRed = Product.create(name: "Supreme S Logo Hooded Sweatshirt (FW18) Red" , img_url: "https://stockx.imgix.net/products/streetwear/Supreme-S-Logo-Hooded-Sweatshirt-FW18-Red.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1539869744&w=1000", description: "Supreme Red S-Logo Hoodie - Season: FW18")
noahGrayHoodie = Product.create(name: "Noah Core Logo Hoodie Heather Grey", img_url: "https://stockx.imgix.net/products/streetwear/Noah-Core-Logo-Hoodie-Heather-Grey.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1545229841&w=1000", description: "Noah Core Logo Hoodie - Heather Grey")
bapeCamoBlackT = Product.create(name: "BAPE 1st Camo Sleeve Pocket Tee Black", img_url: "https://stockx.imgix.net/products/streetwear/BAPE-1st-Camo-Sleeve-Pocket-Tee-Black.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1558403466&w=1000", description: "BAPE 1st Camo Sleeve Pocket Tee - Black")
supremeWhiteT = Product.create(name: "Supreme Gold Bars Tee White", img_url: "https://stockx.imgix.net/products/streetwear/Supreme-Gold-Bars-Tee-White.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1558630012&w=1000", description: "Supreme Gold Bars Tee - White - Season SS19")
palaceGreyHoodie = Product.create(name: "Palace Tablet Hoodie - Grey", img_url: "https://stockx.imgix.net/products/streetwear/Palace-Tablet-Hoodie-Grey-Multi-color.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1538080256&w=1000", description: "Palace Tablet Hoodie Grey/Multi-Color")


# BOTTOMS
camoBeachPants = Product.create(name: "1st Camo Beach Pants", img_url: "https://cdn.shopify.com/s/files/1/0214/3706/products/001SPF301002_YEL_A_large.jpg?v=1558113419", description: "100% Polyester Beach Pants - Yellow Camo")
apeHeadTrackShorts = Product.create(name: "BAPE Ape Head Track Shorts Black", img_url: "https://stockx.imgix.net/products/streetwear/BAPE-Ape-Head-Track-Shorts-Black.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1555366037&w=2200", description: "BAPE Ape head track shorts - black")
nikeTechPantsBlack = Product.create(name: "Nike Tech Pants 'Black'", img_url: "https://www.stadiumgoods.com/media/catalog/product/cache/1/base/1000x600/9df78eab33525d08d6e5fb8d27136e95/n/s/nsw0004_2.png", description: "Big Swoosh x Atmos Edition. Nike Tech Pants - Black - Male")
bapeCamoCargo = Product.create(name: "BAPE 1st Camo 6 Pocket Pants (SS19) Green", img_url: "https://stockx.imgix.net/products/streetwear/Bape-1st-Camo-6-Pocket-Pants-SS19-Green.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1549926251&w=1000", description: "BAPE 1st Camo - 6 Pocket Cargo Pants - Green")
palaceBeigeCargo = Product.create(name: "Palace Cargo Trousers Spring 2016 Beige", img_url: "https://stockx.imgix.net/products/streetwear/Palace-Cargo-Trousers-Spring-2016-Beige.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1538080256&w=1000", description: "Palace Cargo Trousers Spring 2016 Beige")
floralSupremeShorts = Product.create(name: "Supreme Nylon Water Short Black Floral", img_url: "https://stockx.imgix.net/products/streetwear/Supreme-Nylon-Water-Short-Black-Floral.jpg?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1551713097&w=1000", description: "Supreme Nylon Water Short Black Floral - Season - SS18: Release Date: 2018-06-14")

# POSTS 
post1 = Post.create(name: "First Outfit Of The Year", img_url: "https://scontent.cdninstagram.com/vp/76f97bb7f55e2c8079153df8fb19a660/5D554BE2/t51.2885-15/e35/p320x320/56237881_2334136760245868_8944875153641777963_n.jpg?_nc_ht=scontent.cdninstagram.com", views: 0, likes: 0, user_id: brian.id)
post2 = Post.create(name: "Bred 4's The Return!", img_url: "https://scontent.cdninstagram.com/vp/eeaed1daa0938a9b120da1aa2a82a988/5D9BE5B1/t51.2885-15/e35/s320x320/59572164_141543396980093_2253470431074373026_n.jpg?_nc_ht=scontent.cdninstagram.com", views: 0, likes: 0, user_id: brian.id)
post3 = Post.create(name: "Travi! YUH!", img_url: "https://scontent.cdninstagram.com/vp/b103639c0f7f29e3e1c4374dbbc4e560/5D9ACCCF/t51.2885-15/e35/p320x320/58737538_1290363617788618_4205048715173578764_n.jpg?_nc_ht=scontent.cdninstagram.com", views: 0, likes: 0, user_id: brian.id)
post4 = Post.create(name: "OffWhite x Jawden Uno, Get At Me!", img_url: "https://scontent.cdninstagram.com/vp/6814276b865435e5d5f8e1a97c49d8c6/5D9F8234/t51.2885-15/e35/s320x320/57311724_769207123474790_4489078662096435745_n.jpg?_nc_ht=scontent.cdninstagram.com", views: 0, likes: 0, user_id: brian.id)
post5 = Post.create(name: "Palace At The Beach", img_url: "https://scontent.cdninstagram.com/vp/c87ce966eb1543a43bbfb019913257e9/5D968613/t51.2885-15/e35/s320x320/59265566_291979398407315_7282558010052910238_n.jpg?_nc_ht=scontent.cdninstagram.com", views: 0, likes: 0, user_id: brian.id)
post6 = Post.create(name: "Waves on Waves on Waves", img_url: "https://www.aiobot.com/wp-content/uploads/2018/08/adidas-yeezy-700-waverunner.jpg", views: 0, likes: 0, user_id: brian.id)


# PARTS
part1 = Part.create(post_id: post1.id, product_id: shatterAway.id)
part2 = Part.create(post_id: post1.id, product_id: bapeCamoCargo.id)
part3 = Part.create(post_id: post1.id, product_id: noahGrayHoodie.id)

part4 = Part.create(post_id: post2.id, product_id: bred4.id)

part5 = Part.create(post_id: post3.id, product_id: raidBlackFOG.id)
part6 = Part.create(post_id: post3.id, product_id: bapeCamoCargo.id)
part7 = Part.create(post_id: post3.id, product_id: bapeCamoBlackT.id)

part8 = Part.create(post_id: post4.id, product_id: offWhiteChicago.id)
part9 = Part.create(post_id: post4.id, product_id: palaceBeigeCargo.id)
part10 = Part.create(post_id: post4.id, product_id: supremeWhiteT.id)

part11 = Part.create(post_id: post5.id, product_id: wotherspoon.id)
part12 = Part.create(post_id: post5.id, product_id: floralSupremeShorts.id)
part13 = Part.create(post_id: post5.id, product_id: palaceGreyHoodie.id)

part14 = Part.create(post_id: post6.id, product_id: waverunner.id)
